### ISSUE TITLE
[feature request] reverse indexing of mouse events

### ISSUE THREAD

**Issue by milroc** [ayasdi/grapher#1]
Given a point [x, y] find the nearest node or edge.

I don't want to prescribe an implementation, but from the d3.js community, typically a voronoi is computed for this use case.

**Comment by cixzhang** [comment]
To clarify, will [x, y] be in the pixel space (ex. offsets on the DOM) or the data space (relative to the node and link x, y coordinates)?

**Comment by milroc** [comment]
[x, y] in pixelSpace, similar to: http://bl.ocks.org/mbostock/7608400 only updating dynamically.

**Comment by cixzhang** [comment]
An update:
We're currently working on v1 of Grapher which will bring in our own renderers (removing the need for PIXI). Since this is version 1, we'r setting the scope for Grapher to only deal with rendering the network and management of the canvas.

Hit target detection from mouse events isn't something that readily fits into this scope, but I'd be happy to provide a plugin that does this and a system for custom builds so you can build Grapher with hit target detection.

I'm also interested to hear what others think Grapher's scope should be.

**Comment by cixzhang** [comment]
Grapher now has the following functions for converting between pixel and data positions:

    grapher.getDataPosition(x, y); // converts display position to data position
    grapher.getDisplayPosition(x, y); // converts data position to display position

Grapher.target module (https://github.com/ayasdi/grapher-target) now does the reverse indexing including a nearest function for finding the nearest node or link.

**Comment by milroc** [comment]
Cindy,

Thanks this is exactly the thing I was looking for. Looking forward to
playing with it.

-Miles
