### ISSUE TITLE
Grapher take CPU

### ISSUE THREAD

**Issue by security-database** [ayasdi/grapher#20]
Hello

It seem that grapher take some CPU on Force layout

For exemple, 40 nodes -> 
- Canvas only, when animation stop -> CPU about 15-16% (canvas.html)
- Grapher, when animation stop -> CPU about 65-70% (grapher.html)

Is that normal ?

Test files available here : 
https://github.com/security-database/vdna-crosslinks-canvas/tree/master/grapher_speedtest

**Comment by cixzhang** [comment]
That's interesting. On initial glance, it could be because the canvas implementation re-renders on the force tick, whereas grapher.play will render grapher in a renderAnimationFrame loop. So, possibly grapher is simply rendering more often in the grapher implementation. Though, it could very well be that grapher does do extra computations when passing along to the WebGL renderer and this would take up a bit more CPU than a Canvas renderer.

Thanks for sending your sample! I'll look into this a bit more tomorrow :)

**Comment by security-database** [comment]
If i profile grapher.html (CPU under Chrome) when animation "stop" i can see that Grapher.animate still continue. If it can help.

**Comment by cixzhang** [comment]
Try this:

Instead of calling ```grapher.play()``` on line 121, call ```grapher.render()``` in the ```onTick``` function after ```grapher.update()```.

This should give a more accurate comparison vs. your canvas implementation since now they're both updating and rendering when the force layout ticks.

The reason ```grapher.animate``` will still continue when you call ```grapher.play``` is because ```grapher.play``` will call ```grapher.animate``` in an infinite renderAnimationFrame loop. To stop the animation loop you can call ```grapher.stop```.

**Comment by security-database** [comment]
How ! Impressing, done to 9% ! Thanks a lot, understand a lot more now ;)
